server:
  port: 10800
  tomcat:
    max-connections: 600000

spring:
  security:
    user:
      name: admin
      password: admin
  profiles:
    active: dev
  application:
    name: irh-monitor
  cloud:
    config:
      username: admin
      password: admin

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"


eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka   # 注册到eureka注册中心
  instance:
    lease-renewal-interval-in-seconds: 5      # 心跳时间
    lease-expiration-duration-in-seconds: 15  # 过期时间
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${server.port}