server:
  port: 10800

spring:
  profiles:
    active: dev
  application:
    name: irh-monitor
  cloud:
    config:
      username: admin
      password: admin

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka   # 注册到eureka注册中心
  instance:
    lease-renewal-interval-in-seconds: 5      # 心跳时间
    lease-expiration-duration-in-seconds: 15  # 过期时间