server:
  port: 10500

mybatis:
  mapper-locations: /mapper/*
  type-aliases-package: top.imuster.order.api.pojo   #别名扫描

spring:
  profiles:
    active: dev
  application:
    name: order-service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5        # 心跳时间
    lease-expiration-duration-in-seconds: 15    # 过期时间

debug:
  true

logging:
  config: classpath:logback-spring.xml
