server:
  port: 10600
  tomcat:
    max-http-post-size: 4048576
    max-http-header-size: 4048576
spring:
  redis:
    database: 0
    host: 39.105.0.169
    port: 6379
    jedis:
      pool:
        MaxWaitMillis: 100000
        max-active: 100
        max-idle: 20
        min-idle: 10
        max-wait: 5000ms
    timeout: 10000
    password: irh_aliyun_redis
  profiles:
    active: dev
  application:
    name: file-service
  servlet:
    multipart:
      max-file-size: 10MB    #最大文件大小
      max-request-size: 10MB #请求数据大小
enable:
  needLogin: false

feign:
  hystrix:
    enabled: true
  httpclient:
    connection-timeout: 6000

hystrix:
  command:
    default:  #default全局有效，service id指定应用有效
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000 #断路器超时时间，默认1000ms

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
#fdfs:
#  so-timeout: 1501 # 读取超时时间
#  connect-timeout: 5001 # 连接超时时间
#  thumb-image: # 缩略图
#    width: 60
#    height: 60
#  tracker-list: # tracker地址：你的虚拟机服务器地址+端口（默认是22122）
#    - 192.168.174.129:22122