server:
  port: 8085

spring:
  profiles:
    active: dev
  redis:
    database: 0
    host: 39.105.0.169
    port: 6379
    jedis:
      pool:
        max-active: 30
        max-idle: 10
        max-wait: -1
    timeout: 1000

  application:
    name: user-service

  datasource:
      druid:
        driver-class-name: com.mysql.jdbc.Driver
        username: root
        password: 197877346hmr
        url: jdbc:mysql://39.105.0.169:3306/irh?characterEncoding=UTF-8&amp;useUnicode=true&amp;allowMultiQueries=true
        initial-size: 5     # 初始化大小
        max-active: 20      # 连接池中最大的活动数
        max-wait: 30000                             # 最大连接等待时间
        time-between-eviction-runs-millis: 60000    # 配置检测可以关闭的空闲连接间隔时间
        validation-query: select '1' from dual      # 测试连接
  rabbitmq:
    host: 39.105.0.169
    port: 5672
    username: admin
    password: 197877346hmr

eureka:
  client:
    service-url:
      defaultZone: http://39.105.0.169:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5        # 心跳时间
    lease-expiration-duration-in-seconds: 15    # 过期时间

mybatis:
  mapper-locations: mapper/*
  type-aliases-package: top.imuster.user.api.pojo  #别名扫描

feign:
  hystrix:
    enabled: true

logging:
  level:
    top.imuster.user: debug

hot:
  topic:
    total: 30   # 显示热搜数量
    refreshTime: 30    #总热度榜刷新时间

enable:
  needLogin: false

secure:
  ignored:
    urls: #安全路径白名单
      - /swagger-ui.html
      - /swagger-resources/**
      - /swagger/**
      - /**/v2/api-docs
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.ico
      - /webjars/springfox-swagger-ui/**
      - /actuator/**
      - /druid/**
      - /admin/login
      - /admin/register
      - /customer/login
      - /customer/register
      - /error
      - /user/feign/login/
      - /user/feign/roleAndAuth









