server:
  port: 10000

spring:
  application:
    name: security-service
  profiles:
    active: prod

auth:
  tokenValiditySeconds: 1200  #token存储到redis的过期时间
  clientId: irhWebApp
  clientSecret: irhWebApp
  cookieDomain: localhost
  cookieMaxAge: -1
encrypt:
  key-store:
    location: classpath:/irh.keystore
    secret: irhkeystore
    alias: irhkey
    password: imuster

hot:
  topic:
    total: 30   # 显示热搜数量
    refreshTime: 30    #总热度榜刷新时间

logging:
  level:
    top.imuster.auth: debug

management:
  security:
    enabled: false

ribbon:
  MaxAutoRetries: 2 #最大重试次数，当Eureka中可以找到服务，但是服务连不上时将会重试，如果eureka中找不到服务则直接走断路器
  MaxAutoRetriesNextServer: 3 #切换实例的重试次数
  OkToRetryOnAllOperations: false  #对所有操作请求都进行重试，如果是get则可以，如果是post，put等操作没有实现幂等的情况下是很危险的,所以设置为false
  ConnectTimeout: 5000  #请求连接的超时时间
  ReadTimeout: 6000 #请求处理的超时时间
