server:
  port: 10000

spring:
  application:
    name: security-service
  profiles:
    active: dev

mybatis:
  mapper-locations: mapper/*
  type-aliases-package: top.imuster.security.pojo

auth:
  tokenValiditySeconds: 1200  #token存储到redis的过期时间
  clientId: irhWebApp
  clientSecret: irhWebApp
  cookieDomain: localhost
  cookieMaxAge: -1
encrypt:
  key-store:
    location: classpath:/irh.keystore
    secret: irhkeystore
    alias: irhkey
    password: imuster

hot:
  topic:
    total: 0   # 显示热搜数量
    refreshTime: 0    #总热度榜刷新时间

logging:
  level:
    top.imuster.auth: debug

management:
  security:
    enabled: false

baidu:    # 调用百度AI的accessToken
  accessToken: 24.d3d15caaab162df7a0405664a9ae7091.2592000.1587978125.282335-19129665    # access token
  templateSign: 86a4cc9321bfc4fa106ba2a6d374ce56    # 识别一卡通的模板id
  bdRecogniseUrl: https://aip.baidubce.com/rest/2.0/solution/v1/iocr/recognise

aliyun:
  realNameAuth:
    host: http://dm-51.data.aliyun.com
    path: /rest/160601/ocr/ocr_idcard.json
    appCode: 00840a9616a643ee8d98e323d938ef5f

ribbon:
  MaxAutoRetries: 2 #最大重试次数，当Eureka中可以找到服务，但是服务连不上时将会重试，如果eureka中找不到服务则直接走断路器
  MaxAutoRetriesNextServer: 3 #切换实例的重试次数
  OkToRetryOnAllOperations: false  #对所有操作请求都进行重试，如果是get则可以，如果是post，put等操作没有实现幂等的情况下是很危险的,所以设置为false
  ConnectTimeout: 5000  #请求连接的超时时间
  ReadTimeout: 6000 #请求处理的超时时间


secure:
  ignored:
    urls: #安全路径白名单
      - /swagger-ui.html
      - /swagger-resources/**
      - /swagger/**
      - /**/v2/api-docs
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.ico
      - /webjars/springfox-swagger-ui/**
      - /actuator/**
      - /druid/**
      - /admin/login
      - /admin/register
      - /customer/login
      - /customer/register
      - /error
      - /user/feign/login/
      - /user/feign/roleAndAuth