server:
  port: 443

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
    registry-fetch-interval-seconds: 5           # 设置拉取服务的间隔时间

logging:
  level:
    root: warn