eureka:
  client:
    service-url:
      defaultZone: http://39.97.123.63:10086/eureka
    registry-fetch-interval-seconds: 5           # 设置拉取服务的间隔时间

logging:
  level:
    root: error

spring:
  redis:
    database: 0
    host: 39.105.0.169
    port: 6379
    lettuce:
      pool:
        max-active: 30
        max-idle: 10
        max-wait: 5000ms
    timeout: 10000ms
    password: irh_aliyun_redis