eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
    registry-fetch-interval-seconds: 5           # 设置拉取服务的间隔时间

logging:
  level:
    root: info

spring:
  redis:
    database: 0
    host: localhost
    port: 6379
    lettuce:
      pool:
        max-active: 100
        max-idle: 20
        min-idle: 10
        max-wait: 5000ms
    timeout: 10000ms