eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
    registry-fetch-interval-seconds: 5           # 设置拉取服务的间隔时间

logging:
  level:
    root: info

spring:
  redis:
    database: 0
    host: 39.105.0.169
    port: 6379
    jedis:
      pool:
        MaxWaitMillis: 100000
        max-active: 100
        max-idle: 20
        min-idle: 10
        max-wait: 5000
    timeout: 10000
    password: irh_aliyun_redis