eureka:
  client:
    service-url:
      defaultZone: http://39.105.0.169:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5        # 心跳时间
    lease-expiration-duration-in-seconds: 15    # 过期时间
server:
  port: 10100
spring:
  application:
    name: message-service

  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: 197877346hmr
      url: jdbc:mysql://39.105.0.169:33306/irh?characterEncoding=UTF-8&amp;useUnicode=true&amp;allowMultiQueries=true;useAffectedRows=true
      initial-size: 5     # 初始化大小
      max-active: 20      # 连接池中最大的活动数
      max-wait: 30000                             # 最大连接等待时间
      time-between-eviction-runs-millis: 60000    # 配置检测可以关闭的空闲连接间隔时间
      validation-query: select '1' from dual      # 测试连接

  rabbitmq:
    host: 39.105.0.169
    port: 5672
    username: admin
    password: 197877346hmr

  mail:
    username: 1978773465@qq.com
    password: srxhdikamojzbajg
    host: smtp.qq.com

irh:
  elasticsearch:
    host: 39.97.121.108:9200
  goods:     #商城模块索引
    index: goods
    type: doc
    source_field: id,productName,mainPicUrl,st,mt,salePrice,originalPrice,tradeType,originalPrice,productDesc
  forum:     #论坛模块索引
    index: forum
    type: doc
    source_field: id,mainPictureUrl,title,st,mt

mybatis:
  mapper-locations: /mapper/*
  type-aliases-package: top.imuster.message.pojo

logging:
  config: classpath:logback-spring.xml

enable:
  needLogin: false

