server:
  port: 10300

management:
  endpoints:
    web:
      exposure:
        include: '*'
        exclude:
  endpoint:
    health:
      show-details: always

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: top.imuster.life.api.pojo

spring:
  profiles:
    active: dev
  application:
    name: forum-service

feign:     # 启动hystrix
  hystrix:
    enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5        # 心跳时间
    lease-expiration-duration-in-seconds: 15    # 过期时间

logging:
  level:
    top.imuster: debug


browse:   # redis中存储的浏览记录
  record:
    size: 30    #存储的链表大小
    expire: 180 #过期时间    单位为 天
