server:
  port: 10086
spring:
  profiles:
    active: dev
  application:
    name: irh-registry
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        exclude: '*'