spring:
  redis:
    database: 0
    host: 39.105.0.169
    port: 6379
    jedis:
      pool:
        max-active: 30
        max-idle: 10
        max-wait: -1
    timeout: 1000
    password: 197877346h

