server:
  port: 10400

mybatis:
  mapper-locations: /mapper/*
  type-aliases-package: top.imuster.goods.api.pojo   #别名扫描

spring:
  profiles:
    active: dev
  application:
    name: goods-service

logging:
  config: classpath:logback-spring.xml

image.fileTypes:
  - jpg
  - png
  - bmp

feign:    # 启动hystrix
  hystrix:
    enabled: true
