server:
  port: 10400

mybatis:
  mapper-locations: classpath:mapper/*
  type-aliases-package: top.imuster.goods.api.pojo   #别名扫描
  configuration:
    default-executor-type: simple

spring:
  data:
    mongodb:
      uri: mongodb://101.200.87.195:27017/irh_recommender
  profiles:
    active: dev
  application:
    name: goods-service

logging:
  config: classpath:logback-spring.xml
  level:
    top.imuster.goods: debug

feign:    # 启动hystrix
  hystrix:
    enabled: true
