server:
  port: 10400

mybatis:
  mapper-locations: /mapper/*
  type-aliases-package: top.imuster.goods.api.pojo   #别名扫描

spring:
  data:
    mongodb:
      uri: mongodb://101.200.87.195:27017/recommender
  profiles:
    active: dev
  application:
    name: goods-service

logging:
  config: classpath:logback-spring.xml
  level:
    top.imuster.goods: debug

image.fileTypes:
  - jpg
  - png
  - bmp

feign:    # 启动hystrix
  hystrix:
    enabled: true
