server:
  port: 10400

mybatis:
  mapper-locations: classpath:mapper/*
  type-aliases-package: top.imuster.goods.api.pojo   #别名扫描
  configuration:
    default-executor-type: simple

spring:
  data:
    mongodb:
      port: 21083
      username: imuster
      password: 123imuster456
      database: irh_recommender
      host: 101.200.87.195
      authentication-database: admin
  profiles:
    active: dev
  application:
    name: goods-service

logging:
  config: classpath:logback-spring.xml
  level:
    top.imuster.goods: debug

feign:    # 启动hystrix
  hystrix:
    enabled: true

secure:
  ignored:
    urls: #安全路径白名单
      - /swagger-ui.html
      - /swagger-resources/**
      - /swagger/**
      - /**/v2/api-docs
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.ico
      - /webjars/springfox-swagger-ui/**
      - /actuator/**
      - /druid/**
      - /error
      - /goods/feign/**